// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr1nt69YyhTIW-72Ldd9X7bELtA2Hka9s',
    appId: '1:34121371148:web:de61dd5eaa4252fc40e829',
    messagingSenderId: '34121371148',
    projectId: 'poligo-7762f',
    authDomain: 'poligo-7762f.firebaseapp.com',
    storageBucket: 'poligo-7762f.appspot.com',
    measurementId: 'G-W7CM5WM4S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeyie5cDDEWCjpH30GVPHG-UJqvLpmKiI',
    appId: '1:34121371148:android:16706698d18f671840e829',
    messagingSenderId: '34121371148',
    projectId: 'poligo-7762f',
    storageBucket: 'poligo-7762f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQLQkwEcxMA95qFuvm58JbUyCRTqYdfUw',
    appId: '1:34121371148:ios:12e09c0fc276f05c40e829',
    messagingSenderId: '34121371148',
    projectId: 'poligo-7762f',
    storageBucket: 'poligo-7762f.appspot.com',
    androidClientId: '34121371148-qac7l9lq1kdjgq2mu08o58i8uqvmua19.apps.googleusercontent.com',
    iosClientId: '34121371148-2cn9dh9eecvb4q77pelcp67mmmeb3t5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.poligo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQLQkwEcxMA95qFuvm58JbUyCRTqYdfUw',
    appId: '1:34121371148:ios:12e09c0fc276f05c40e829',
    messagingSenderId: '34121371148',
    projectId: 'poligo-7762f',
    storageBucket: 'poligo-7762f.appspot.com',
    androidClientId: '34121371148-qac7l9lq1kdjgq2mu08o58i8uqvmua19.apps.googleusercontent.com',
    iosClientId: '34121371148-2cn9dh9eecvb4q77pelcp67mmmeb3t5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.poligo',
  );
}
